name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: sudo apt install sdcc
      
    - name: clean
      run: make clean
      
    - name: make
      run: make
      
    - name: eeprom
      run: make eeprom
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcu-artifact
        path: |
        main.hex
        eeprom.hex
